### ISSUE TITLE
python2.7?

### ISSUE THREAD

**Issue by paris007** [tayyabt/tprocess#1]
Hi, I have a very naive question. Seems like your code works for python 3.4. I am trying to run my code with python 2.7. Any idea how I should make it work with v2.7? 

Thanks!

**Comment by paris007** [comment]
simpler than I thought : pip3 install git+http://github.com/tayyabt/tprocess 'python>=2.7'

**Comment by paris007** [comment]
Now I got a different error - 

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/Users/paris/anaconda/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Users/paris/anaconda/lib/python2.7/threading.py", line 763, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/Users/paris/anaconda/lib/python2.7/site-packages/tprocess/tprocess.py", line 79, in get_output
    m = re.search( exp, self.before )
  File "/Users/paris/anaconda/lib/python2.7/re.py", line 146, in search
    return _compile(pattern, flags).search(string)
  File "/Users/paris/anaconda/lib/python2.7/re.py", line 237, in _compile
    p, loc = _cache[cachekey]
TypeError: unhashable type: 'list'
